service: s1m-monorepo-api
org: simonphumin
app: s1m-monorepo-api

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-optimize

provider:
    name: aws
    runtime: nodejs18.x
    region: us-west-1
    stage: ${opt:stage, 'dev'}

functions:
    api:
        handler: ./apps/api/src/lambda.main
        events:
            - http:
                  cors: true
                  method: any
                  path: /{any+}
            - http:
                  cors: true
                  method: any
                  path: /
